
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "guimurgel@gmail.com",
    "password": "123456"
}

###
DELETE  http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYwMjcxMTAwN30.TZqGA5ZcmQefJPXNPyn1JEi7C2RBUBfk2xeLOsfxTZ8"
}


